spring:
  application:
    name: linan-characteristic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      max-lifetime: 1200000
      maximum-pool-size: 10
server:
  port: 9090
  servlet:
    context-path: /api
logging:
  level:
    com.lomtom: debug
mybatis:
  mapperLocations: classpath:mapper/*/*.xml
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true

